### ISSUE TITLE
light==yellow

### ISSUE THREAD

**Issue by tofr** [BianoBonzoIII/otter_Space#2]
Exciting. Unprecedented in annals of apcs history. 

Need details on meaningful use of term2 concepts

**Comment by SashaKor** [comment]
This project will use the concept of trees and nodes covered in term2. Each SolarSystem will be a tree-like structure that allows for the adding of celestial bodies at regular intervals (nodes). Planets will be akin to children in the tree structure and moons are children of planets (since they orbit around planets). Collisions would lead to removal of corresponding nodes from the System and a change in the visual.
